### ISSUE TITLE
Improvement: Use all available free GPU memory for tracing 

### ISSUE THREAD

**Issue by SimeonEhrig** [NetroScript/GPU-memory-access-visualization#4]
**Only if some time is left!**

You can ask the CUDA runtime, how much free memory is left: http://horacio9573.no-ip.org/cuda/group__CUDART__MEMORY_gd5d6772f4b2f3355078ecd6059e6aa74.html

Could be a good default value for `CudaMemAccessStorage`, if it takes all memory minus a small security buffer (it can cause some bugs, if you really allocate all memory). The option to set the size of the buffer should still exist.

**Comment by NetroScript** [comment]
Closing as with the current library arbitrary sizes can be chosen, even if they do not fit into VRAM, due to using Unified Memory.
